# Generated by Django 2.2.28 on 2024-03-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BrewReview', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=128)),
                ('post_code', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='shop_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BrewReview.Addresses'),
        ),
        migrations.CreateModel(
            name='SavedReviews',
            fields=[
                ('save_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_id', models.ManyToManyField(to='BrewReview.Review')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteShops',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.ManyToManyField(to='BrewReview.CoffeeShop')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='shop_id',
            field=models.ManyToManyField(to='BrewReview.CoffeeShop'),
        ),
    ]
