# Generated by Django 2.2.28 on 2024-03-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0003_auto_20240306_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='favouriteshops',
            options={'verbose_name_plural': 'FavouriteShops'},
        ),
        migrations.AlterModelOptions(
            name='savedreviews',
            options={'verbose_name_plural': 'SavedReviews'},
        ),
    ]
