# Generated by Django 2.2.28 on 2024-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0005_auto_20240306_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favouriteshops',
            name='fav_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savedreviews',
            name='save_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
