# Generated by Django 2.2.28 on 2024-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0007_auto_20240306_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='long',
            new_name='lng',
        ),
    ]
