# Generated by Django 2.2.28 on 2024-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0010_auto_20240310_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='slug',
            field=models.SlugField(),
        ),
    ]
