# Generated by Django 2.2.28 on 2024-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0011_auto_20240310_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
