# Generated by Django 2.2.28 on 2024-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0012_auto_20240310_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='lng',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='address',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
