# Generated by Django 2.2.28 on 2024-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0014_auto_20240315_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='address_line_1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='city',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='country',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
