# Generated by Django 2.2.28 on 2024-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0017_userprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
