# Generated by Django 2.2.28 on 2024-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0018_auto_20240319_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='image_location_folder',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='picture',
            field=models.ImageField(blank=True, upload_to='shop_images'),
        ),
    ]
