# Generated by Django 2.2.28 on 2024-03-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrewReview', '0020_auto_20240321_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedreviews',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='savedreviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavouriteShops',
        ),
        migrations.DeleteModel(
            name='SavedReviews',
        ),
    ]
